services:
  gts-rss:
    build: .
    volumes:
      - ./config:/app/config
  redis:
    image: redis:alpine
    command: "redis-server --save 60 1 --loglevel warning"
    volumes:
      - ./data:/data
