services:
  rss-goes-social:
#    build: .
    image: anhgelus/rss-goes-social
    volumes:
      - ./config:/app/config
  redis:
    image: redis:alpine
    command: "redis-server --save 60 1 --loglevel warning"
    volumes:
      - ./data:/data
